FLAGS = `root-config --cflags`
LIBS = `root-config --libs`

scatterAll.x: scatterAll.C
	g++ scatterAll.C -o scatterAll.x $(FLAGS) $(LIBS)

histoAll.x: histoAll.C
	g++ histoAll.C -o histoAll.x $(FLAGS) $(LIBS)



